# Generated by Django 4.2.11 on 2024-04-17 00:30

from django.db import migrations, models
import django.db.models.deletion
import reports.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficViolation',
            fields=[
                ('license_plate', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('violation', models.CharField(choices=[('Red line parking', 'Red line parking'), ('Yellow line parking', 'Yellow line parking'), ('Driving on pedestrian path', 'Driving on pedestrian path'), ('Failure to yield to pedestrians', 'Failure to yield to pedestrians'), ('Changing lanes without signaling', 'Changing lanes without signaling'), ('Parking on pedestrian path', 'Parking on pedestrian path'), ('Parking on sidewalk', 'Parking on sidewalk'), ('Running a red light', 'Running a red light'), ('Tailgating', 'Tailgating'), ('Failure to yield to oncoming traffic', 'Failure to yield to oncoming traffic'), ('Not following lane markings', 'Not following lane markings'), ('Other', 'Other')], max_length=100)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Not approved', 'Not approved'), ('Other', 'Other')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user_input_type', models.CharField(blank=True, max_length=100, null=True)),
                ('officer', models.CharField(blank=True, default='', max_length=255)),
                ('traffic_violation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reports.models.PathAndRename(''))),
                ('traffic_violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.trafficviolation')),
            ],
        ),
    ]
